### ISSUE TITLE
Yakuake supports sixel

### ISSUE THREAD

**Issue by MenacingPerson** [smasher164/arewesixelyet#1]
It's based on konsole so it does.

**Comment by brjsp** [comment]
Yakuake does not reuse code from konsole, it loads konsole as a dynamic library, so it would make sense there are no refernces in code. I just tested on current Tumbleweed and sixel graphics indeed work on yakuake.

**Comment by smasher164** [comment]
Thank you for confirming this. I will update the page accordingly. Do you happen to know when (what release) Yakuake started supporting SIXEL?

**Comment by Samisafool** [comment]
I do not know, sadly. Close this issue if you'd like
