### ISSUE TITLE
DomTerm supports sixel

### ISSUE THREAD

**Issue by PerBothner** [smasher164/arewesixelyet#14]
Website: https://domterm.org
Sources: https://github.com/PerBothner/DomTerm/

DomTerm has had sixel support since 2019, but I made major changes/improvements in March 2023.

**Comment by smasher164** [comment]
Thanks for filing this! I see from your repo that you first documented SIXEL support in version 2.1. Is that correct?
Is there a changelog entry I can link to? No worries if not.

**Comment by PerBothner** [comment]
I'm not very conscientious about version numbers, but it looks like DomTerm version 2.0 (September 2019) had sixel support (added January 2019).

**Comment by smasher164** [comment]
Thanks!

**Comment by PerBothner** [comment]
Thanks for maintaining this list.
