### ISSUE TITLE
Missing Blackbox terminal

### ISSUE THREAD

**Issue by rice7th** [smasher164/arewesixelyet#9]
Hello,
recently I've discovered the [BlackBox](https://gitlab.gnome.org/raggesilver/blackbox) terminal, and It supports Sixel, though it is still in beta.

**Comment by iambumblehead** [comment]
The status of Blackbox should be changed. Blackbox does not support sixel. Along with Tilix, Gnome Terminal and Guake it relies on [upstream VTE,](https://gitlab.gnome.org/raggesilver/blackbox/-/merge_requests/101) where sixels are disabled as default

**Comment by smasher164** [comment]
Ah good catch. Let me reopen this issue and make the corresponding update. Thanks!
